import localFont from 'next/font/local';

import '../styles/globals.css';

import Providers from '@/providers';

const pretendard = localFont({
	src: '../../public/fonts/PretendardVariable.woff2',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

// export default function RootLayout({
// 	children,
// 	modal,
// }: {
// 	children: React.ReactNode;
// 	modal: React.ReactNode;
// }) {
// 	return (
// 		<html lang='ko' suppressHydrationWarning>
// 			<body className={pretendard.className}>
// 				<Providers>
// 					<div className='h-full'>{children}</div>

// 					<div className='__portal'>{modal}</div>
// 				</Providers>
// 			</body>
// 		</html>
// 	);
// }
export default function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	return (
		<html lang='ko' suppressHydrationWarning>
			<body className={'m-0 '}>
				<Providers>
					{/* <div className='h-[50px] bg-blue-900 relative z-10'></div> */}
					<div className='rootLayout h-screen overflow-auto'>
						{children}
					</div>

					{/* <div className='__portal'>{modal}</div> */}
					{/* <div className='w-full h-[90px] bg-green-950 z-10'></div> */}
				</Providers>
			</body>
		</html>
	);
}
